{{- if .Values.apiRule.enabled }}
apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ include "slate.fullname" . }}
  labels:
    {{- include "slate.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.apiRule.gateway }}
  hosts:
  {{- if .Values.apiRule.customDomain }}
  - {{ .Values.apiRule.customDomain }}
  {{- else }}
  - {{ .Values.apiRule.host }}
  {{- end }}
  {{- if and .Values.apiRule.tls.enabled .Values.apiRule.tls.secretName }}
  tls:
    secretName: {{ .Values.apiRule.tls.secretName }}
  {{- end }}
  rules:
    - path: /*
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
      service:
        {{- if .Values.approuter.enabled }}
        name: {{ include "slate.fullname" . }}-approuter
        port: {{ .Values.approuter.service.port }}
        {{- else }}
        name: {{ include "slate.fullname" . }}-frontend
        port: {{ .Values.frontend.service.port }}
        {{- end }}
      noAuth: true
{{- end }}
