apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slate.fullname" . }}-config
  labels:
    {{- include "slate.labels" . | nindent 4 }}
data:
  API_HOST: {{ .Values.backend.env.apiHost | quote }}
  API_PORT: {{ .Values.backend.env.apiPort | quote }}
  DATABASE_TYPE: {{ .Values.backend.database.type | quote }}
  SQLITE_DB_PATH: {{ .Values.backend.database.path | quote }}
  LOG_LEVEL: {{ .Values.backend.env.logLevel | quote }}
  {{- if .Values.xsuaa.enabled }}
  XSUAA_ENABLED: {{ .Values.backend.env.xsuaaEnabled | default "true" | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slate.fullname" . }}-destinations
  labels:
    {{- include "slate.labels" . | nindent 4 }}
data:
  destinations: |
    [
      {
        "name": "{{ .Values.destinations.backend.name }}",
        "url": "{{ .Values.destinations.backend.url }}",
        "forwardAuthToken": {{ .Values.destinations.backend.forwardAuthToken }}
      },
      {
        "name": "{{ .Values.destinations.frontend.name }}",
        "url": "{{ .Values.destinations.frontend.url }}",
        "forwardAuthToken": {{ .Values.destinations.frontend.forwardAuthToken }}
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slate.fullname" . }}-xs-app
  labels:
    {{- include "slate.labels" . | nindent 4 }}
data:
  xs-app.json: |
    {
      "authenticationMethod": "{{ .Values.xsApp.authenticationMethod }}"
      {{- if .Values.xsApp.welcomeFile }},
      "welcomeFile": "{{ .Values.xsApp.welcomeFile }}"
      {{- end }}
      {{- if .Values.xsApp.sessionTimeout }},
      "sessionTimeout": {{ .Values.xsApp.sessionTimeout }}
      {{- end }},
      "routes": {{ .Values.xsApp.routes | toJson }}
    }
