{{- if .Values.sapAiCoreApi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: slate-sap-ai-core-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: slate
type: Opaque
stringData:
  authUrl: {{ .Values.sapAiCoreApi.credentials.authUrl | quote }}
  clientId: {{ .Values.sapAiCoreApi.credentials.clientId | quote }}
  clientSecret: {{ .Values.sapAiCoreApi.credentials.clientSecret | quote }}
  baseUrl: {{ .Values.sapAiCoreApi.credentials.baseUrl | quote }}
  resourceGroup: {{ .Values.sapAiCoreApi.credentials.resourceGroup | quote }}
{{- end }}
