#!/bin/bash

echo "🧹 Clearing XSUAA Session"
echo "=========================="
echo ""
echo "To clear your XSUAA session and test fresh login:"
echo ""
echo "1. Open Browser DevTools (F12)"
echo "2. Go to Application tab"
echo "3. Select Cookies → http://localhost:5001"
echo "4. Right-click → Clear all cookies"
echo ""
echo "Or use this JavaScript in Console:"
echo ""
echo "document.cookie.split(';').forEach(c => {" 
echo "  document.cookie = c.trim().split('=')[0] + '=;expires=Thu, 01 Jan 1970 00:00:00 UTC;path=/;';"
echo "});"
echo ""
echo "Then refresh the page: http://localhost:5001"
echo ""
echo "Expected flow:"
echo "1. Redirects to XSUAA login"
echo "2. Login with SAP credentials"  
echo "3. After login, frontend checks session"
echo "4. Auto-redirects to dashboard"
