-- Orchestration Executions Table (HANA)
-- Stores all autonomous orchestration executions
CREATE COLUMN TABLE orchestration_executions (
    id NVARCHAR(36) PRIMARY KEY,
    user_id NVARCHAR(36) NOT NULL,
    notebook_id NVARCHAR(36),
    goal NCLOB NOT NULL,
    status NVARCHAR(50) NOT NULL,  -- starting, analyzing, planning, spawning, executing, synthesizing, completed, failed, cancelled
    orchestration_mode NVARCHAR(20),  -- single, team, swarm
    team_id NVARCHAR(36),

    -- Analysis results
    complexity NVARCHAR(20),
    intent NVARCHAR(100),
    required_capabilities NCLOB,  -- JSON array

    -- Execution plan
    execution_plan NCLOB,  -- JSON
    parallel_groups NCLOB,  -- JSON array of arrays

    -- Current progress
    current_phase NVARCHAR(50),
    progress REAL DEFAULT 0.0,

    -- Results
    result NCLOB,  -- JSON
    error NCLOB,

    -- Timestamps
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (notebook_id) REFERENCES notebooks(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES agent_teams(id) ON DELETE SET NULL
);

CREATE INDEX idx_orchestration_user_id ON orchestration_executions(user_id);
CREATE INDEX idx_orchestration_status ON orchestration_executions(status);
CREATE INDEX idx_orchestration_started_at ON orchestration_executions(started_at);
CREATE INDEX idx_orchestration_team_id ON orchestration_executions(team_id);


-- Orchestration Events Table (HANA)
-- Stores timestamped events during orchestration
CREATE COLUMN TABLE orchestration_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orchestration_id NVARCHAR(36) NOT NULL,
    event_type NVARCHAR(100) NOT NULL,  -- orchestration.started, decision.made, task.assigned, etc.
    event_data NCLOB NOT NULL,  -- JSON
    timestamp TIMESTAMP NOT NULL,

    FOREIGN KEY (orchestration_id) REFERENCES orchestration_executions(id) ON DELETE CASCADE
);

CREATE INDEX idx_orchestration_events_orchestration ON orchestration_events(orchestration_id);
CREATE INDEX idx_orchestration_events_type ON orchestration_events(event_type);
CREATE INDEX idx_orchestration_events_timestamp ON orchestration_events(timestamp);


-- Orchestration Resources Table (HANA)
-- Links orchestrations to resources used (tools, sources, agents)
CREATE COLUMN TABLE orchestration_resources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orchestration_id NVARCHAR(36) NOT NULL,
    resource_type NVARCHAR(50) NOT NULL,  -- tool, source, agent, mcp_server
    resource_id NVARCHAR(36) NOT NULL,
    resource_name NVARCHAR(500),
    usage_count INTEGER DEFAULT 0,

    FOREIGN KEY (orchestration_id) REFERENCES orchestration_executions(id) ON DELETE CASCADE
);

CREATE INDEX idx_orchestration_resources_orchestration ON orchestration_resources(orchestration_id);
CREATE INDEX idx_orchestration_resources_type ON orchestration_resources(resource_type);


-- Orchestration Metrics Table (HANA)
-- Performance metrics for orchestrations
CREATE COLUMN TABLE orchestration_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orchestration_id NVARCHAR(36) NOT NULL,

    -- Timing metrics
    analysis_duration_ms INTEGER,
    decision_duration_ms INTEGER,
    spawning_duration_ms INTEGER,
    planning_duration_ms INTEGER,
    execution_duration_ms INTEGER,
    synthesis_duration_ms INTEGER,
    total_duration_ms INTEGER,

    -- Execution metrics
    task_count INTEGER DEFAULT 0,
    parallel_task_count INTEGER DEFAULT 0,
    sequential_task_count INTEGER DEFAULT 0,
    handover_count INTEGER DEFAULT 0,

    -- Resource metrics
    agent_count INTEGER DEFAULT 0,
    tool_call_count INTEGER DEFAULT 0,
    llm_token_usage INTEGER DEFAULT 0,

    -- Efficiency metrics
    speedup_ratio REAL,  -- parallel vs sequential time
    resource_utilization REAL,  -- 0.0 to 1.0

    created_at TIMESTAMP NOT NULL,

    FOREIGN KEY (orchestration_id) REFERENCES orchestration_executions(id) ON DELETE CASCADE
);

CREATE INDEX idx_orchestration_metrics_orchestration ON orchestration_metrics(orchestration_id);


-- Orchestration Config Table (HANA)
-- User-specific orchestration preferences
CREATE COLUMN TABLE orchestration_configs (
    id NVARCHAR(36) PRIMARY KEY,
    user_id NVARCHAR(36) NOT NULL,

    -- Mode preferences
    prefer_team_over_single BOOLEAN DEFAULT FALSE,
    prefer_swarm_over_team BOOLEAN DEFAULT FALSE,

    -- Execution preferences
    max_team_size INTEGER DEFAULT 10,
    max_concurrent_tasks INTEGER DEFAULT 5,
    enable_parallel_execution BOOLEAN DEFAULT TRUE,

    -- Resource limits
    max_execution_duration_seconds INTEGER DEFAULT 600,
    max_llm_tokens_per_orchestration INTEGER DEFAULT 100000,

    -- LLM model selection
    decision_model NVARCHAR(100),
    planner_model NVARCHAR(100),
    synthesizer_model NVARCHAR(100),

    -- Timestamps
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_orchestration_configs_user ON orchestration_configs(user_id);
