apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slate-backend-data
  labels:
    app: slate
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
