namespace: grtest-ns
global:
  domain: c-83567d2.kyma.ondemand.com
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: gokulraj18/slate-backend
    tag: kyma-v1.0.3
    pullPolicy: Always
  persistence:
    enabled: true
    size: 20Gi
    accessMode: ReadWriteOnce
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
sapAiCoreApi:
  enabled: true
  replicaCount: 1
  image:
    repository: gokulraj18/slate-sap-ai-core-api
    tag: v1.0.0
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  credentials:
    authUrl: https://sapit-core-playground-vole.authentication.eu10.hana.ondemand.com
    clientId: ***REMOVED-AICORE-CLIENT-ID***
    clientSecret: ***REMOVED-AICORE-CLIENT-SECRET***
    baseUrl: https://api.ai.prod.eu-central-1.aws.ml.hana.ondemand.com
    resourceGroup: ***REMOVED-AICORE-RESOURCE-GROUP***
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: gokulraj18/slate-frontend
    tag: kyma-v1.0.7
    pullPolicy: Always
  env:
    nodeEnv: production
    nextTelemetryDisabled: "1"
    xsuaaEnabled: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
approuter:
  enabled: true
  replicaCount: 2
  image:
    repository: gokulraj18/slate-approuter
    tag: kyma-v1.0.6
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
xsuaa:
  enabled: true
  xsappname: slate-grtest
ingress:
  enabled: true
  host: slate-grtest.c-83567d2.kyma.ondemand.com
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  tls:
    enabled: true
  rules:
  - path: /.*
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    - OPTIONS
    accessStrategies:
    - handler: noop
apiRule:
  enabled: true
  host: slate-grtest.c-83567d2.kyma.ondemand.com
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  tls:
    enabled: true
  rules:
  - path: /.*
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    - OPTIONS
    accessStrategies:
    - handler: noop
xsApp:
  authenticationMethod: route
  welcomeFile: /index.html
  routes:
  - source: ^/api/(.*)$
    target: /api/$1
    destination: backend
    authenticationType: xsuaa
  - source: ^/(.*)$
    target: /$1
    localDir: resources
    authenticationType: xsuaa
